---
name: Wallet Bug Reporter
about: Report any issues found in the Wallet App
title: ''
labels: bug
assignees: ''

---

body:
  - type: markdown
    attributes:
      value: |


  - type: textarea
    id: bug-description
    attributes:
      label: bug
      description: Write a brief description of what you were trying to do, and what happened..
      placeholder: 1. I was trying to do ... 
    validations:
      required: true

  - type: Phone Type
    id: device-type
    attributes:
      label: Phone Type
      description: What Operating System (iOS or Android) and what OS Version (i.e. iOS 14 or Android 12.0)
      placeholder: ex. iPhone 13 iOS 15
    validations:
      required: true
